// This file is generated by cli and will be overwritten
export const SDK_PATH =  "/Users/gauravgautam/apptile-cli-home/ReactNativeTSProjeect";
export const APP_ID = "1efc8fa1-a80f-48b6-bb8e-95d0ec6b9a4c";
export const CLI_BASE_URL = "192.168.11.174:3100/plugin-server";
// export const APPTILE_BACKEND_URL = "http://api.apptile.local";
// export const APPTILE_BACKEND_URL = "http://192.168.11.174:3001";
export const APPTILE_BACKEND_URL = "https://dev-api.apptile.io";
export const APPCONFIG_SERVER_URL = "https://dev-appconfigs.apptile.io";

export const FacebookAppID =  '570147808995354'
export const FacebookClientToken = '5c95639f9583bc38a9fea5075b04b1cf'
export const FacebookDisplayName =  'Pilgrim Staging'
export const FacebookAutoLogAppEventsEnabled = 'YES'
export const FacebookAdvertiserIDCollectionEnabled = 'NO'

export const appsflyerDevkey = 'xxx';
export const appsflyerAppId = 'xxx';
export const ENABLE_APPSFLYER = false;

export const MOENGAGE_APPID = 'xxx';
export const MOENGAGE_DATACENTER = 'data_center_0';

export const feature_flags = {
  ENABLE_FBSDK: false,
  ENABLE_FIREBASE_ANALYTICS: false,
  ENABLE_MOENGAGE_ANALYTICS: false,
  ENABLE_APPSFLYER: false
}
