// This file is generated by cli and will be overwritten
export const SDK_PATH =  "/Users/sahilgoyal/apptile-cli-home/ReactNativeTSProjeect";
export const APP_ID = "f19473fa-4434-49e4-82c0-ca060221eae9";
export const CLI_BASE_URL = "127.0.2.2:3100/plugin-server";
export const APPTILE_BACKEND_URL = "https://api.apptile.io";
export const APPCONFIG_SERVER_URL = "https://appconfigs.apptile.io";
